// Niche templates — plain JS objects, no dependencies
const BRAND_TEMPLATES = {
  autoescola: {
    label: 'Autoescola / CFC', icon: '🚗',
    data: {
      name: 'Nova Autoescola', niche: 'Autoescolas / CFCs',
      tagline: 'Gestão profissional para escolas de trânsito',
      positioning: 'Autoridade em gestão operacional e pedagógica de CFCs. Conteúdo sério, dado-driven, voltado para gestores que querem controle e crescimento sustentável.',
      tone_main: 'Autoritário e direto', tone_reader: 'Você (formal)',
      tone_never: 'Nunca usar gírias. Evitar humor. Proibido exclamações em excesso.',
      style_visual: 'Tech e moderno',
      color_primary: '#1E3A8A', color_secondary: '#3B82F6', color_accent: '#FACC15',
      color_dark: '#0F172A', color_light: '#EFF6FF', color_text: '#F8FAFC',
      audience: 'Proprietários e gestores de autoescolas, 35–60 anos, que já têm operação rodando mas sentem que poderiam crescer mais com mais organização.',
      pain: 'Perdem alunos por falta de acompanhamento e não têm visibilidade financeira do negócio.',
      desire: 'Ter controle total da escola, faturar mais e não depender de planilhas.',
      personality: ['Direto', 'Técnico', 'Confiável', 'Objetivo'],
      goals: ['Educar gestores', 'Gerar autoridade', 'Gerar leads'],
      topics: ['Gestão de alunos', 'Inadimplência', 'Legislação de trânsito', 'Marketing para CFCs', 'Financeiro'],
      post_frequency: '3× por semana',
    }
  },
  nutricionista: {
    label: 'Nutricionista / Saúde', icon: '🥗',
    data: {
      name: 'Nutrição Inteligente', niche: 'Nutrição e Saúde',
      tagline: 'Ciência aplicada à alimentação de verdade',
      positioning: 'Profissional que alia evidência científica com linguagem acessível. Sem extremismos, sem dietas milagrosas.',
      tone_main: 'Consultivo e educativo', tone_reader: 'Você (informal)',
      tone_never: 'Nunca prometer resultados milagrosos. Evitar termos muito técnicos sem explicação. Proibido desinformação.',
      style_visual: 'Orgânico e humano',
      color_primary: '#166534', color_secondary: '#4ADE80', color_accent: '#FDE68A',
      color_dark: '#14532D', color_light: '#F0FDF4', color_text: '#FAFAFA',
      audience: 'Mulheres 25–45 anos que buscam emagrecer ou melhorar a saúde sem precisar de dietas restritivas.',
      pain: 'Já tentaram várias dietas sem sucesso e não sabem o que realmente funciona para o próprio corpo.',
      desire: 'Ter uma relação saudável com a comida e alcançar o peso ideal de forma sustentável.',
      personality: ['Acolhedor', 'Empático', 'Científico', 'Prático'],
      goals: ['Educar', 'Gerar confiança', 'Agendar consultas'],
      topics: ['Alimentação saudável', 'Mitos da dieta', 'Receitas', 'Emagrecimento', 'Micronutrientes'],
      post_frequency: 'Diário',
    }
  },
  saas_b2b: {
    label: 'SaaS / Tech B2B', icon: '💻',
    data: {
      name: 'Plataforma SaaS', niche: 'Software B2B / Tech',
      tagline: 'Automatize o que te atrasa',
      positioning: 'Produto que resolve um problema específico de negócio. Tom técnico mas acessível, foco em ROI e eficiência operacional.',
      tone_main: 'Técnico e objetivo', tone_reader: 'Você (formal)',
      tone_never: 'Nunca ser genérico. Evitar buzzwords vazios. Proibido prometer o que o produto não entrega.',
      style_visual: 'Tech e moderno',
      color_primary: '#4F46E5', color_secondary: '#818CF8', color_accent: '#34D399',
      color_dark: '#1E1B4B', color_light: '#EEF2FF', color_text: '#F9FAFB',
      audience: 'Gestores e diretores de empresas de médio porte, 30–50 anos, que sofrem com processos manuais e falta de dados confiáveis para decidir.',
      pain: 'Perdem tempo e dinheiro com processos manuais, planilhas desatualizadas e falta de integração entre ferramentas.',
      desire: 'Ter uma operação mais eficiente com visibilidade em tempo real e menos retrabalho.',
      personality: ['Direto', 'Confiável', 'Inovador', 'Focado em resultado'],
      goals: ['Gerar leads qualificados', 'Educar sobre o problema', 'Demonstrar ROI'],
      topics: ['Automação', 'Produtividade', 'Gestão de dados', 'Integração de sistemas', 'Cases de sucesso'],
      post_frequency: '3× por semana',
    }
  },
  infoproduto: {
    label: 'Infoproduto / Curso Online', icon: '🎓',
    data: {
      name: 'Infoprodutor Expert', niche: 'Educação Online / Infoprodutos',
      tagline: 'Do zero ao resultado com método comprovado',
      positioning: 'Expert que já conquistou resultado e agora ensina o caminho mais curto para quem quer o mesmo. Autoridade pessoal + prova social.',
      tone_main: 'Inspiracional e motivacional', tone_reader: 'Você (informal)',
      tone_never: 'Nunca parecer fake ou genérico. Evitar promessas que não pode cumprir. Proibido termos de guruzismo vazio.',
      style_visual: 'Bold e agressivo',
      color_primary: '#B45309', color_secondary: '#F59E0B', color_accent: '#FFFFFF',
      color_dark: '#1C1917', color_light: '#FFFBEB', color_text: '#FAFAF9',
      audience: 'Pessoas 25–45 anos que querem aprender uma habilidade ou mudar de carreira, mas não sabem por onde começar ou como acelerar.',
      pain: 'Já compraram outros cursos que não entregaram resultado. Sentem que estão rodando em círculos.',
      desire: 'Ter clareza do caminho, começar a ver resultado rápido e se sentir seguras para avançar.',
      personality: ['Motivador', 'Honesto', 'Provocativo', 'Expert'],
      goals: ['Gerar desejo pelo curso', 'Construir autoridade', 'Gerar matrículas'],
      topics: ['Transformação pessoal', 'Habilidades práticas', 'Bastidores', 'Depoimentos', 'Dicas do nicho'],
      post_frequency: 'Diário',
    }
  },
  moda: {
    label: 'Moda / Lifestyle', icon: '👗',
    data: {
      name: 'Marca de Moda', niche: 'Moda e Estilo',
      tagline: 'Vista quem você quer ser',
      positioning: 'Marca que vende estilo de vida, não apenas roupas. Conteúdo aspiracional com identidade visual forte e estética coesa.',
      tone_main: 'Premium e sofisticado', tone_reader: 'Você (informal)',
      tone_never: 'Nunca parecer genérico ou fast fashion. Evitar descrições técnicas sem emoção. Proibido excesso de promoção.',
      style_visual: 'Minimalista e limpo',
      color_primary: '#1C1917', color_secondary: '#A8A29E', color_accent: '#D97706',
      color_dark: '#0C0A09', color_light: '#FAFAF9', color_text: '#1C1917',
      audience: 'Mulheres 22–40 anos com renda média-alta, que se importam com estética e querem se expressar pelo que vestem.',
      pain: 'Sentem dificuldade de montar looks que realmente combinem com sua personalidade sem gastar muito.',
      desire: 'Ter um guarda-roupa cápsula que funcione para qualquer ocasião e que reflita quem elas são.',
      personality: ['Sofisticado', 'Aspiracional', 'Autêntico', 'Editorial'],
      goals: ['Aumentar desejo de compra', 'Construir comunidade', 'Gerar vendas diretas'],
      topics: ['Looks do dia', 'Combinações', 'Tendências', 'Bastidores', 'Estilo de vida'],
      post_frequency: 'Diário',
    }
  },
  consultoria: {
    label: 'Consultoria / Serviços B2B', icon: '📊',
    data: {
      name: 'Consultoria Estratégica', niche: 'Consultoria / Serviços Profissionais',
      tagline: 'Estratégia que transforma resultado',
      positioning: 'Consultoria de alto nível que fala para decisores. Conteúdo sério, denso, que demonstra profundidade de conhecimento e gera credibilidade.',
      tone_main: 'Editorial e jornalístico', tone_reader: 'Você (formal)',
      tone_never: 'Nunca ser superficial. Evitar conteúdo genérico de autoajuda. Proibido linguagem de coach.',
      style_visual: 'Premium e editorial',
      color_primary: '#1E293B', color_secondary: '#475569', color_accent: '#F1C40F',
      color_dark: '#0F172A', color_light: '#F8FAFC', color_text: '#F8FAFC',
      audience: 'CEOs, diretores e sócios de empresas de médio porte que enfrentam desafios estratégicos de crescimento, eficiência ou transformação.',
      pain: 'Sentem que a empresa cresceu mas a estrutura não acompanhou. Decisões importantes sendo tomadas no feeling.',
      desire: 'Ter clareza estratégica, uma equipe alinhada e resultados previsíveis e escaláveis.',
      personality: ['Especialista', 'Direto', 'Premium', 'Confiável'],
      goals: ['Gerar autoridade', 'Atrair clientes de alto ticket', 'Educar decisores'],
      topics: ['Estratégia empresarial', 'Liderança', 'Eficiência operacional', 'Cases', 'Análises de mercado'],
      post_frequency: '3× por semana',
    }
  },
};

window.BRAND_TEMPLATES = BRAND_TEMPLATES;
